export const INIT_FIREBASE = "INIT_FIREBASE";
export const LOGIN_USER = "LOGIN_USER";
export const REFRESH_BUDGETS = 'REFRESH_BUDGETS';
export const REFRESH_SAVINGS = 'REFRESH_SAVINGS';
export const SET_EDITING_REF = 'SET_EDITING_REF'